### ISSUE TITLE
Don't ask microphone permission in android

### ISSUE THREAD

**Issue by alexbaforvo** [nstudio/nativescript-audio#104]
Hi,
I'm using the plugin to play some mp3 files in my app, but I don't use the microphone at any moment. In my androidManifest.xml I haven't added the specific permission request, but when I install the app from Google Play, the request is asked anyway.

How can I change that?

**Comment by bradmartin** [comment]
Nothing in the plugin would cause the permission prompt. You Gabe to
execute the method to request permission. Can you share some of your code
or a project. This plugin will add the permissions to your manifest during
the Android build but the prompt had to be triggered by the app. Hope that
helps some. My best guess without seeing the project is you have some logic
requesting permission

**Comment by alexbaforvo** [comment]
Hi,

this is the code where the plugin is used, only the playerFromFile method is instanciated, and from other parts of the projects I call to my "playFromFile" method

```
import { TNSPlayer } from 'nativescript-audio';
import { checkFile, getAbsolutePath } from './file.util';

export const playFromFile = (audioFile: string, completeCallback = null) => {
  const player = new TNSPlayer();
  if (checkFile(audioFile)) {
    player.playFromFile({ audioFile: getAbsolutePath(audioFile), loop: false, completeCallback});
  }

  return player;
};
```

**Comment by bradmartin** [comment]
What device and API are you running on? Wondering if a new API has changed permissions somewhat.

**Comment by alexbaforvo** [comment]
My app is intended to work on android (also on iOS) phones and tablets with mininum SDK version 17 (target SDK 27). I have used nativescript 3.4.1 + typescript 2.6.2

**Comment by alexbaforvo** [comment]
I have found the AndroidManifest.xml file in the platform/android folder of the nativescript-audio node_modules folder. Is it safe to remove the `<uses-permission android:name="android.permission.RECORD_AUDIO"/>` line?

**Comment by bradmartin** [comment]
It is safe to remove, you don't want to have to modify your node_modules
though bc that's not a good solution. Having that permission in the
manifest doesn't trigger the permission prompt though during the app's
lifecycle. The permission method has to be called or a recording has to be
attempted so I'm honestly not sure how you are getting the prompt without
calling the permission method :/ sorry

**Comment by alexbaforvo** [comment]
Maybe I have no explained well my issue (sorry for my english). The permission is asked in the app installation, not during any moment of the lifecycle, because it is not used (no recording). I was trying to avoid that initial request of microphone at the installation process, and removing the line in the manifest solved the problem.

So for me it's ok to close the issue :)

**Comment by outsideMyBox** [comment]
I also ran into this problem. I solved it temporarily by removing the line in AndroidManifest.xml but perhaps it shouldn't be part of the extension.

**Comment by bradmartin** [comment]
Great solution might be to have a `post-install` hook that asks if you're going to use Recorder so it's not a default. Documenting this would be crucial also to avoid people asking about the missing permission.

**Comment by GabrielCamba** [comment]
Ill take it.

**Comment by tauling** [comment]
> I also ran into this problem. I solved it temporarily by removing the line in AndroidManifest.xml but perhaps it shouldn't be part of the extension.

Simply removing the permission request from the Manifest didn't work for me. Did you change something else in addition?

**Comment by mehdinourollah** [comment]
> Great solution might be to have a `post-install` hook that asks if you're going to use Recorder so it's not a default. Documenting this would be crucial also to avoid people asking about the missing permission.

Can you explain more ? How can i make it auto to remove RECORD_AUDIO permissions from node_modules ( perhaps in mediafilepicker plugin !!)
