### ISSUE TITLE
scrubber

### ISSUE THREAD

**Issue by bradrice** [nstudio/nativescript-audio#109]
Is there a way to get emitted current Time values to make sure a scrubber is in sync with where the audio is? I've been trying to just do an interval, but the code is turning to spaghetti with the play/pause, stop, turn the page stuff going on in my app.

**Comment by bradmartin** [comment]
If just trying to sync the remaining time with duration the demo app might be helpful here: https://github.com/nstudio/nativescript-audio/blob/master/demo/app/main-view-model.ts#L305

**Comment by bradrice** [comment]
Thanks Brad. I wasn't aware of the demo app.

**Comment by joshnickleby** [comment]
It would be very helpful to have this feature. The current implementation that I have made (based of a similar function to the demo) causes the player to stutter at every hit of the interval
