### ISSUE TITLE
Android: player plays last initialized sound after finishing a call

### ISSUE THREAD

**Issue by jnorkus** [nstudio/nativescript-audio#111]
To reproduce, add this code, then receive and finish a phone call. The audio file is played immediately.

```
const player = new TNSPlayer();
player.initFromFile({
  audioFile: '~/audio/audio.mp3',
  loop: false
});
```

**Comment by jnorkus** [comment]
I found the cause of this bug. On Android every time AUDIOFOCUS_GAIN is fired on AudioManager, resume() is called even though the player was not playing when focus was lost.

**Comment by juliancesar** [comment]
Did you get a workaound?

**Comment by jnorkus** [comment]
I did. I commented out the line and now use a local copy of the plugin. Quick and dirty but unfortunately no time to contribute.

**Comment by juliancesar** [comment]
https://github.com/nstudio/nativescript-audio/blob/02017d8b55abe9b0973662b0ecd6dc5529135015/src/android/player.ts#L393

@jnorkus, that line?

@NathanWalker, how can we improve this? Do you have any suggest?

**Comment by jnorkus** [comment]
Yes exactly that one.

**Comment by caiusCitiriga** [comment]
Any news on this guys?

**Comment by Robbt** [comment]
So I guess that someone just needs to put a pull request together to remove this.resume() ? 
I commented out that line and the sounds still played. I don't know yet if it fixed the notification issue.

**Comment by nikolasdas** [comment]
Any news about this? :/

**Comment by bryanlilly** [comment]
My work around for this (in a local version of the plugin) was to make the following edits in `./nativescript-audio/android/player.js`:

``` // Added to player.js line 11
this._resumeOnFocus = false;` added around line 11```
``` if(_this._resumeOnFocus) {
     _this.resume();
      _this._resumeOnFocus = false;
``}

**Comment by bryanlilly** [comment]
Otherwise, the above edits work in my actual app.

**Comment by Addeu** [comment]
I think I have an issue relative to this one. Player plays last initialized audio after colling and closing Google Assistant.  This thing helped:

> 
> 
> I did. I commented out the line and now use a local copy of the plugin. Quick and dirty but unfortunately no time to contribute.

**Comment by szgozcan** [comment]
I had exactly the same problem. Player plays last initializes audio even the app is in background when receives call or notification. #111 (comment) helped.

**Comment by Omar-Al-Ashi** [comment]
In my case, [this answer](https://github.com/nstudio/nativescript-audio/issues/148#issuecomment-490522070)  fixed it 👍🏽
