### ISSUE TITLE
Android context is undefined

### ISSUE THREAD

**Issue by sohailalam2** [nstudio/nativescript-audio#112]
**app.android.context** is _**undefined**_ in https://github.com/nstudio/nativescript-audio/blob/master/src/android/player.ts#L367 

and is causing an uncaught exception getting thrown in [NativeScript Vue](https://nativescript-vue.org/) application

```
JS: [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'getSystemService' of undefined"
```

**Comment by rigor789** [comment]
When are you calling the `TNSPlayer`? The android app may not be started yet.

**Comment by sohailalam2** [comment]
@rigor789 I tried initializing TNSPlayer in **created** and even with **mounted** lifecycle hook... both didn't work! 

Refer: https://vuejs.org/v2/guide/instance.html

**Comment by rigor789** [comment]
`created` is fired when the Vue instance is created - the application is not started yet
`mounted` is fired when the Views are instantiated - but not guaranteed that the app is started yet

`application.launchEvent` is used internally in NativeScript-Vue to mount the application so the application is started **after** the `application.launchEvent`

https://github.com/nativescript-vue/nativescript-vue/blob/e29d47c944f955f973c3e657ad18243f08b747d1/platform/nativescript/runtime/index.js#L63

Can you try `this.$nextTick(() => this.player = new TNSPlayer())`, or a `setTimeout(() =>  this.player = new TNSPlayer())` and check if that fixes it?

**Comment by sohailalam2** [comment]
Perfect this did the trick for me - 

```js
import * as application from 'tns-core-modules/application';

// ....

created() {
    application.on(application.launchEvent, () => {
        this.$nextTick(() => this.player = new TNSPlayer());
    });
},
```

**Comment by Mia12344** [comment]
how can we solve this in nativescript angular ?
