### ISSUE TITLE
Hooking up a nativescript-audio recording with the Google Speech API

### ISSUE THREAD

**Issue by suparnavg** [nstudio/nativescript-audio#114]
Hello, thanks for this fantastic plugin. Super easy to set up and start using.

As the title suggests I'm recording audio using the nativescript-audio plugin, storing it to cloud, then transcribing it using the Google Speech to text API. Creating this issue because I'm facing an encoding configuration problem and I want to verify that I'm using the plugin correctly.

The types of encoding permitted by Google speech API are given in this [table here](https://cloud.google.com/speech-to-text/docs/encoding)

This plugin allows me to set the [androidFormat ](https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat.html#THREE_GPP)and [androidEncoder ](https://developer.android.com/reference/android/media/MediaRecorder.AudioEncoder.html#AMR_WB)variables, along with sample rate.

I've been trying various combinations of these but keep getting the "bad encoding" error from the Google Speech API.

Here is the configuration that I'm most certain will work - but it doesn't seem to.

```
androidEncoder = 2 (AMR_WB);
androidFormat = 1 (3gp);
sampleRate = 16000;
platformExtension = '3gp';
contentType = 'audio/3gpp';
```

For reference, this is the [android developer documentation ](https://developer.android.com/guide/topics/media/media-formats#audio-codecs)that maps the encoding to various file formats. (AMR_WB is mapped to 3gp).

I've checked the uploaded file and it is playing perfectly in a regular media player. So does not seem to be an inherent file corruption issue.

Would appreciate any help on this issue!

Thanks!

**Comment by suparnavg** [comment]
For future readers, in case it helps:

Config used in nativescript-audio:
```
androidFormat = 4; // AMR_WB
androidEncoder = 2; // AMR_WB
platformExtension = '3gp'; // corresponds to AMR_WB encoding
sampleRate: 16000;  // required as per Google speech API docs
metering: false;
```
Store the audio with contentType `'audio/3gpp'`

In the transcribe call made to the speech API, make sure to include the encoding in the config variable, like so:
`const config = { languageCode: 'en-US', enableWordTimeOffsets: true, encoding: 'AMR_WB', sampleRateHertz: 16000}`

**Comment by tylerablake** [comment]
@suparnavg Could you provide any more info on this? I am trying to do the same thing but having issues. Email me if that would be easier, blake12321@gmail.com Thanks!

**Comment by suparnavg** [comment]
Hello @tylerablake. Happy to help. Is there any specific issue I provide info on?

I used the nativescript-audio implementation in this repo with the options in my post above, took the captured audio and stored it on Google cloud, then made the speech API call with the config in my earlier post. Working fine for me (not tested in a production environment yet). Turns out as long as you specify the encoding in both places everything works fine.

In case you're also looking to play the audio file, I'm fetching the audio file using the excellent [nativescript-firebase library](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/) and then playing it using nativescript-audio's player.

**Comment by tylerablake** [comment]
Hi @suparnavg Thanks for the reply. Currently not able to get the nativescript-audio plugin to work, wasn't sure if you had to do anything to get it to work for you. I'm using TS + Angular, are you also using that? Did you have to do anything outside of the quick start guide from the readme?
