### ISSUE TITLE
Demo App Crashes

### ISSUE THREAD

**Issue by tylerablake** [nstudio/nativescript-audio#118]
Trying to see the demo app to implement NS-Audio into an app but can't seem to get the demo app to run on simulator or iPhone device. 

Error when running the demo in simulator:
`JavaScript error:
file:///app/main-view-model.js:3:35: JS ERROR Error: Could not find module 'nativescript-audio'. Computed path '/Users/tyler/Library/Developer/CoreSimulator/Devices/E12CDE8B-BF3F-4F6B-9042-18F5B14E2345/data/Containers/Bundle/Application/5742D6E4-B4F1-4D33-BC65-213ED71DAFA6/demo.app/app/tns_modules/nativescript-audio'.`

Just want to record audio and send audio files to backend service so any extra help would be greatly appreciated!

Thanks!

**Comment by bradmartin** [comment]
Should be working, possibly didn't transpile the `src` directory from that error.

Follow the steps added here https://github.com/nstudio/nativescript-audio#demo-app
