### ISSUE TITLE
Recording options for iOS

### ISSUE THREAD

**Issue by cmckni3** [nstudio/nativescript-audio#123]
It would be nice to have recording format options, for example, a 48 KHz wav file. Of course, with a warning about filesize for formats that are lossless.

I am working with the iOS APIs and noticed the [settings](https://developer.apple.com/documentation/avfoundation/avaudioplayer/general_audio_format_settings) are set to `kAudioFormatMPEG4AAC` (AAC), 16 KHz, and 1 channel (mono) with no way to change it in the code.

It looks like the [android recorder](https://github.com/nstudio/nativescript-audio/blob/master/src/android/recorder.ts#L69) supports these options.

**Comment by ihazar** [comment]
Hi @cmckni3,
Did you manage to suggest a PR with variable Recording options for iOS?
I came to the same problem and have modified the plugin code directly, rewriting the original plugin native iOS code in '/ios/recorder.js file', but that's just a patch.

I wonder why the plugin didn't support iOS recording options in the first place.
Are you planning to work on it? Do you have any updates?

**Comment by cmckni3** [comment]
@ihazar I switched projects and hardcoded the options I needed in my fork.

**Comment by cmckni3** [comment]
This issue still needs to happen at some point.

**Comment by ihazar** [comment]
I understand. Thanks. I hardcoded the options I needed in my code as well.
I'll take a weekend and contribute a PR to address this issue with the ability to set iOS recorder options.
