### ISSUE TITLE
No record permission pop-up in release build 

### ISSUE THREAD

**Issue by mfik** [nstudio/nativescript-audio#134]
The permission pop-up for recording in ios doesn't show up in the release build. It does in the debug build. I have tried several fixes, including setting a CFBundleDisplayName and setting NSMicrophoneUsageDescription in the plist and i have tried making changes to the version number and bundleid. The call goes out to the start function, which in turn calls out to the AVAudioSession requestRecordPermission function. All goes well in the debug build, where i can playback the audio file without any issues. Using the latest version of the plugin, version 6.1.0 of the angular components.

`const recorderOptions: AudioRecorderOptions = {
            filename: audioFolder.path + "/" + audioFile,
            metering: true,
            infoCallback: (infoObject) => {
                console.log("File information: " + JSON.stringify(infoObject));
            },
            errorCallback: (errorObject) => {
                console.log("Record Error: " + JSON.stringify(errorObject));
            }
        };
        if (this.recorderState === false) {
            this._recorder.start(recorderOptions).then((result) => {
                this.recorderState = true;
            });
        }`

**Comment by mfik** [comment]
Just for the extra info. Just upgraded nativescript, typescript, angular components, ios / android platforms, etc. to latest versions (7.2.0) and made a new release build. Same outcome, works perfectly on the debug build, no response on the release build.

**Comment by bradmartin** [comment]
I've never seen this myself. So not sure what could be happening 😕 - wish I had more info. Seems strange. 

Have you tried `uglify` and `aot` with your debug build to rule out those build configs. I'm assuming you're using those with your release build at least.

**Comment by mfik** [comment]
Hi Brad, 

Sorry for the late reply. Got arround to working on this today. I have made a new debug build with all webpack options selected, the recorder works fine. Same setting on production build, no permissions screen when i push my button.

I made two movies to show the difference in behaviour. 
> Debug build : https://youtu.be/LlYNgV4-Ri8
> Release build: 

There is no error or output in the console from the debug build. 

My current actions:
> Deleted .cloud, platforms, node_modules, hooks, webpack config, package lock
> Migrated to NS 6.0
> Selected AOT and Uglify for the builds
> I updated everything to the following versions:

Could there be any kind of conflict? I will try making a new project with just the recorder and then one by one adding the plugins. 

```
{
  "nativescript": {
    "id": "nl.REDACTED.REDACTED",
    "tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    }
  },
  "description": "REDACTED",
  "license": "REDACTED",
  "repository": "REDACTED",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "8.0.3",
    "@angular/common": "8.0.3",
    "@angular/compiler": "8.0.3",
    "@angular/core": "8.0.3",
    "@angular/forms": "8.0.3",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.3",
    "@angular/platform-browser-dynamic": "8.0.3",
    "@angular/router": "8.0.3",
    "nativescript-angular": "8.0.3",
    "nativescript-audio": "5.0.4",
    "nativescript-background-http": "3.4.1",
    "nativescript-camera": "4.5.0",
    "nativescript-imagepicker": "6.2.0",
    "nativescript-iqkeyboardmanager": "1.5.1",
    "nativescript-localstorage": "2.0.0",
    "nativescript-modal-datetimepicker": "1.2.0",
    "nativescript-social-share": "1.5.2",
    "nativescript-theme-core": "1.0.6",
    "nativescript-ui-listview": "7.0.1",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-web-image-cache": "5.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "6.5.2",
    "rxjs-compat": "6.5.2",
    "tns-core-modules": "6.0.1",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.3",
    "@nativescript/schematics": "0.6.0",
    "@ngtools/webpack": "8.0.6",
    "codelyzer": "5.1.0",
    "nativescript-dev-webpack": "1.0.2",
    "node-sass": "4.12.0",
    "tslint": "5.18.0",
    "typescript": "3.4.5"
  },
  "readme": "REDACTED",
  "author": "REDACTED"
}
```

**Comment by mfik** [comment]
Finally got it! Don't use knownFolders.currentApp(), it doesn't work. Use : knownFolders.documents(); and all is good!
