### ISSUE TITLE
Increase quality of registration

### ISSUE THREAD

**Issue by progressify** [nstudio/nativescript-audio#136]
Hi, I use your lib for record small registration.
On Android (for now, I have tested only on it), the recording has very low quality.
This is the code I use to instance the recorder class:

```
this.recorderOptions = {
            filename: this.recordedFilePath,
            format: 2,
            encoder: 4,
            bitRate: 384,
            sampleRate: 96000,
            metering: true,
            infoCallback: infoObject => {
                console.log(JSON.stringify(infoObject));
            },
            errorCallback: errorObject => {
                this.isRecording = false;
                console.log(JSON.stringify(errorObject));
            }
        };
```
Have you any idea what can be the problem?
For testing I use a Google Pixel 2 XL and Android Pie

**Comment by Ivanepp2** [comment]
Your code is correct, but your bit rate is too low for good quality.
RecorderOptions.bitRate is passed to native method in android called setAudioEncodingBitRate [https://developer.android.com/reference/android/media/MediaRecorder#setAudioEncodingBitRate(int)](url).
bitRate refers to the audio quality of the stream and sampleRate is the number of samples per unit time. For calculate bit rate use this formula:
 **bitRate = sampleRate × bit depth × channels**
For your configuration bitRate would be 1,536,000 = **96000 * 2 (stereo) * 16 bits (this depends about your encoding and formats)**  (Your result audio with this configuration is gonna be too large)

**Comment by progressify** [comment]
Thanks, now the quality is perfect <3
I will give you feedback on the size of my audio record

**Comment by progressify** [comment]
ok, the audio is perfect and for short registration, I can listen without a problem.
with audio registration > 1,30 minutes I receive this error when I try to "playFromUrl":
{"player":{},"error":1,"extra":-2147483648}

**Comment by Ivanepp2** [comment]
What is the size of your output file?

**Comment by progressify** [comment]
circa 800/900kb
can be the format of the recording?

**Comment by Ivanepp2** [comment]
could be, for my tests I use.
```
format: 2; //android.media.MediaRecorder.OutputFormat.MPEG_4;
androidEncoder = 3; //android.media.MediaRecorder.AudioEncoder.AAC;
```

You can check the audio support by android here https://developer.android.com/guide/topics/media/media-formats
