### ISSUE TITLE
How to adjust Volume during playback?

### ISSUE THREAD

**Issue by inglesuniversal** [nstudio/nativescript-audio#140]
Hi, I tried your example code at NSPlayground and I wanted to reduce the volume to 0.2, here is what I tried but the app simply crashed twice. 

Could you kindly explain how to adjust the volume during playback mode?

  const viewModel = observableModule.fromObject({
    progress: 0,
    isPlaying: false,
    playPause(args) {
      if (player.isAudioPlaying()) {
        player.pause();
      } else {
        player.play();
        player.volume(0.2);  <----- I also tried ('0.2');
      }
    },

**Comment by bradmartin** [comment]
@inglesuniversal - Have you figured out an approach yet?

https://github.com/nstudio/nativescript-audio#tnsplayer-instance-properties

`volume` is a getter/setter on the `TNS_Player` class. 

So the following should work:

```typescript
player.volume = 0.7;
```
