### ISSUE TITLE
Thanks for your feedback

### ISSUE THREAD

**Issue by inglesuniversal** [nstudio/nativescript-audio#141]
Your response on how to set the volume worked like a charm.

Now I want to implement a volume range slider using one of NativeScript components.

I placed a slider component below the play button and I set an initial value of 50, so it is placed in the center.

I wish to grab the value of the slider as soon as the user drags it and send it to a function.

I am using this:

`<Slider id="volume" value="50" drag="{{ updateVolume }}" />`

and the code below to read the value but nothing happens

    updateVolume() {
      console.log('Vol: ' + volume.val());
    }

Any suggestions Mr. NSTUDIO ?

Regards

**Comment by bradmartin** [comment]
Sounds good.

So here is what I'd do. The `slider` has the `value` (like you have in your snippet). You should `bind` the value into your viewmodel `Observable` in plain NS. Angular apps have a different approach for this just FYI.

Anything binded via the NS `Observable` can be listened to for change events. The docs have some guidance here https://docs.nativescript.org/ns-framework-modules/observable#adding-event-listener-and-using-propertychangeevent

**Comment by bradmartin** [comment]
https://play.nativescript.org/?template=play-tsc&id=TczzHW&v=2 This playground should show how.
