### ISSUE TITLE
Android store requesting permission for Audio record even though I am only using player

### ISSUE THREAD

**Issue by bradrice** [nstudio/nativescript-audio#144]
I only want to use the plugin to playback audio, but the Android Store is asking me to give the app permission to record. How can I tell my app it doesn't need to have access to record. I also get a popup on my Apple simulator asking me to give it access, but I really don't need record capability.

**Comment by bradmartin** [comment]
Been thinking about this and I think the next major version release. We are either gonna split the plugin to be audio player and audio recorder and deprecate this one. Then we don't have to worry about the permissions and less footprint for a plugin not using half of the module. Also less code to maintain for specific issues. Not sure when but possibly in next few months if I have free time this is the plan.

For now, you'd need to fork this and modify the plugin to not include the permission and use your fork for the dependency.

**Comment by rahadur** [comment]
My app rejected from Google. only because it's need hidden Permission and i am not send trams & condition URL. but i am only use this plugins for audio player. You should change this plugins name to Audio Recoder.  or fixed update this. i think lots of people face this problem too.

**Comment by Znegl** [comment]
Any news on this?

**Comment by bradmartin** [comment]
The new major for NS7 did remove the default android RECORD_AUDIO permission which manually needs to be added if you plan/intend to do recording in your app @Znegl 👍
