### ISSUE TITLE
error playing remote audio

### ISSUE THREAD

**Issue by joey0xx** [nstudio/nativescript-audio#146]
Im trying to play a remote audio hosted in an azure blob storage, but I get this error when i play it:
```JS: NativeScript-Audio - TNSPlayer [errorCallback, 1]
JS: {
JS: "player": {},
JS: "error": 1,
JS: "extra": -2147483648
JS: }
```

I can play it locally fine without any errors. Tried to see if it was because of the size (only around 4.0 mb) but i also tried uploading another audio to the blob storage that has bigger size and it played fine. Tried on an android 9.0 emulator and android 8.0 device but none of them worked. Then I uploaded it again after playing it locally but still doesnt work.

Below im attaching a project with the local audio and the remote url
[sampleaudioproj.zip](https://github.com/nstudio/nativescript-audio/files/3041010/sampleaudioproj.zip)

**Comment by alexander171294** [comment]
Same here, android 9 nexus 5 emulator.

**Comment by joseatelevoro** [comment]
@NathanWalker we can pay for this bug fix! Is jose brotha!

**Comment by alexander171294** [comment]
I have found solution for this, but i'm not remember how it is D:

**Comment by pabloacastillo** [comment]
> I have found solution for this, but i'm not remember how it is D:

Perhaps something like this @alexander171294 ?

Add an attribute to the ```<application>``` tag in AndroidManifest.xml

    android:usesCleartextTraffic="true"

Hope this helps.

**Comment by jakoguta** [comment]
I am having trouble playing remote files on Android version 10.

```
reference back to player: {
    "player": {},
    "error": 1,
    "extra": -1015
}
```

I have this `android:usesCleartextTraffic="true"` set in AndroidManifest.xml `<application>` tag. I am using `nativescript-audio v6.2.1`, `@nativescript/core v7.0.13`, `angular 11`, and also set `<uses-permission android:name="android.permission.INTERNET"/>`

The streaming works on other devices (Honor, running Android 7) but fail on others (Samsung, running Android 10). Any help to fix this bug would really be appreciated.

**Comment by bradmartin** [comment]
@jakoguta - your error value of `1` https://stackoverflow.com/a/18084143/1893557 indicates the error is unknown. It's possible the audio file might have issues with playback on Samsung devices. Can you share the file you're attempting to play?

**Comment by jakoguta** [comment]
@bradmartin I managed to solve the issue. I was streaming the audio file (.mp3) form a python server, using flask `Response()` function without specifying the `mimetype="audio/mpeg"`.  Other devices would work fine but some needed this to be specified. I hope others may learn from my mistake.
