### ISSUE TITLE
Play 2 songs at the same time

### ISSUE THREAD

**Issue by Ravaniss** [nstudio/nativescript-audio#155]
Hello everyone ! :)

I'm making a song editor with Nativescript, here is my question : How can i play 2 or 3 or ... songs at the same time ?

Thank you ! :)

Regards,
Rav'

**Comment by bradmartin** [comment]
I don't think the native media players support two audio sources at once. So you'll need to create two instances of the audio players to do this.

**Comment by Ravaniss** [comment]
Thank you ! :)

Works like a charm.

Here the code, that will help others too :)

`
async playSing() {
        console.log("play")
        this.player = new audio.TNSPlayer()
        const playerOptions = {
          audioFile: "~/assets/audio/rocks.mp4",
          loop: false
        }

        const secondPlayer = new audio.TNSPlayer()
        const secondPlayerOptions = {
          audioFile: "~/assets/audio/heart.mp4",
          loop: false
        }

        await this.player.playFromUrl(playerOptions)
        await secondPlayer.playFromUrl(secondPlayerOptions
      }
`

**Comment by Ravaniss** [comment]
I'm opening it again because I have a big problem. ^^

I'm making a songs editor :

![image](https://user-images.githubusercontent.com/16159090/66211025-6cca9780-e6bb-11e9-8118-f0c155377a71.png)

When my timeline touch a song, that should play it
for now, with what i have
that play a song, but when that touch another song, that stop the first to launch the second

Here a repo : https://github.com/Ravaniss/song-editor

Someone can help with that please ? <3

**Comment by ralyodio** [comment]
Does it work?
