### ISSUE TITLE
Support Nativescript 6

### ISSUE THREAD

**Issue by ramiroaisen** [nstudio/nativescript-audio#158]
I cant get the plugin running in NS 6.
Theres no logging errors or something like that either, the player never finish loading the file.
is 6.0 supported?

**Comment by LucyTurtle** [comment]
I'm running on 6.2 I believe and the plugin loads the sound files for me (:

Send code sample?

**Comment by ggportfoliowork** [comment]
6.3.0 is working fine for me both iOS and android.  are you trying to play from a file or url?
