### ISSUE TITLE
ogg audio format not playing on iOS

### ISSUE THREAD

**Issue by Omar-Al-Ashi** [nstudio/nativescript-audio#163]
On iOS, .ogg audio format is not loading, whereas on Android it works perfectly without any issues.
Is there a way to load and play .ogg audio?

**Comment by bradmartin** [comment]
Have you checked to see if the native iOS player class being used in this plugin supports that format? 

https://github.com/nstudio/nativescript-audio/blob/master/src/ios/player.ts#L92
`AVAudioPlayer` is what you need to confirm supports that format.

**Comment by Omar-Al-Ashi** [comment]
It turns out "AVAudioPlayer" doesn't support .ogg formats :/
Is there a workaround to play .ogg audio?

**Comment by bradmartin** [comment]
Not with this plugin. Can you search for something on native iOS that supports ogg? If you find it then you'll have a route to take.
