### ISSUE TITLE
Can't build demo app

### ISSUE THREAD

**Issue by Znegl** [nstudio/nativescript-audio#175]
I just tried running the Demo App following the instructions in README.md but sadly I'm running into the following error on both Android and iOS:

`No project found at or above '/Users/thomas/PhpstormProjects/nativescript-audio/demo' and neither was a --path specified.`

**Comment by bradmartin** [comment]
I'll review the readme.

Do you have the latest NS CLI installed? If not run, `npm uninstall -g nativescript && npm i -g nativescript` and that will get the latest CLI, which that might be why you encountered this issue.

**Comment by Znegl** [comment]
I ran into some local permission issues while trying to update, but I'll get back to you as soon as I have it up and running.

Thank you for the quick reply!
