### ISSUE TITLE
Android/ios no sound

### ISSUE THREAD

**Issue by Upd4ting** [nstudio/nativescript-audio#181]
Hey

I can use this plugin the way I want (playFromFile, playFromURL, remote url, local url) it doesn't work. I'm always getting `abandonAudioFocusRequest...result... 1` any idea ?

**Comment by LaKing** [comment]
Just run into this too ... is there a solution?

**Comment by asharghi** [comment]
Same here

**Comment by asharghi** [comment]
Works for me after adding a rule for copying mp3 files in the new webpack config:

`webpack.Utils.addCopyRule("audio/**/*")`

<img width="827" alt="Screenshot 2021-05-01 at 03 42 27" src="https://user-images.githubusercontent.com/9407896/116767287-8b2b7d00-aa2f-11eb-8fd0-d85bcdf630a9.png">

**Comment by Upd4ting** [comment]
@LaKing I had to do the same things as @asharghi

**Comment by LaKing** [comment]
Great! ... Thanks !!!
