### ISSUE TITLE
When i install nativecsript-audio, i get following error

### ISSUE THREAD

**Issue by PirithiviAR** [nstudio/nativescript-audio#88]
Installing...
Successfully installed on device with identifier 'b589d2bf'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.audio on device b589d2bf.
Executing before-watch hook from E:\hi\AVPT\nativescript-audio-master\demo\hooks\before-watch\nativescript-dev-typescript.js
Found peer TypeScript 2.5.3
ActivityManager: Start proc 15440:org.nativescript.audio/u0a217 for activity org.nativescript.audio/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.audio/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-audio", relative to: app/tns_modules/
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "nativescript-audio", relative to: app/tns_modules/
System.err:     at com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     at com.tns.Module.resolvePath(Module.java:55)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6705)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
System.err:     ... 9 more
ActivityManager: Process org.nativescript.audio (pid 15440) has died
ActivityManager: cleanUpApplicationRecord -- 15440
15:18:53 - Compilation complete. Watching for file changes.

**Comment by PirithiviAR** [comment]
Please help me to solve this problem

**Comment by bradmartin** [comment]
This error: `Failed to find module: "nativescript-audio", relative to: app/tns_modules/` would indicate your app is not built with the module correctly. Delete the node_modules/platforms directories and rebuild with a fresh platform setup of the app. If you're running the demo app, there are some scripts in the package.json that will make sure the TS is transpiled to .js to execute.
