### ISSUE TITLE
Streaming audio

### ISSUE THREAD

**Issue by dirkjan** [nstudio/nativescript-audio#91]
It seems to be necessary for all the audio to load before it can be played. I would like the audio be streamable. My server allows it: on the website the same audio-file can be played before it has been fully loaded.

**Comment by darioperez** [comment]
Same for me. i'm trying to consume a shoutcast stream and it seems to be waiting until download ends and, of course, that won't happen. any idea?

**Comment by bradmartin** [comment]
On Android from docs: `Note: If you're passing a URL to stream an online media file, the file must be capable of progressive download.` I believe this works by default with Android MediaPlayer - could definitely use another set of eyes to spot anything the plugin might be missing [here](https://developer.android.com/guide/topics/media/mediaplayer.html). 
As for iOS - I'm not familiar with the [AVAudioPlayer](https://developer.apple.com/documentation/avfoundation/avaudioplayer) so maybe someone can review to see how streaming audio works on it.
If someone finds some information and needs help integrating just ping me here and I'd be glad to help someone with a PR or add the pieces myself if it's nothing too time consuming. Thanks 😄

**Comment by darioperez** [comment]
Working with shoutcast :smiley: in android

**Comment by bradmartin** [comment]
Closing for #99
