### ISSUE TITLE
iOS cant play audio. JS ERROR TypeError: null is not an object

### ISSUE THREAD

**Issue by ptdede** [nstudio/nativescript-audio#92]
Hi! I run the app on Emulator and i got this error : 

```
1   0x10df363bb NativeScript::FFICallback<NativeScript::ObjCBlockCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10e5f228e ffi_closure_unix64_inner
3   0x10e5f2bd2 ffi_closure_unix64
4   0x113030a6d __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke
5   0x10ec6b9b7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
6   0x10ec6b81a -[NSBlockOperation main]
7   0x10ec69cd6 -[__NSOperationInternal _start:]
8   0x1140ab2b5 _dispatch_client_callout
9   0x1140b0565 _dispatch_block_invoke_direct
10  0x1140ab2b5 _dispatch_client_callout
11  0x1140b0565 _dispatch_block_invoke_direct
12  0x1140b0401 dispatch_block_perform
13  0x10ec65ce4 __NSOQSchedule_f
14  0x1140ab2b5 _dispatch_client_callout
15  0x1140b1232 _dispatch_continuation_pop
16  0x1140afa93 _dispatch_async_redirect_invoke
17  0x1140b5a72 _dispatch_root_queue_drain
18  0x1140b57dc _dispatch_worker_thread3
19  0x11456a1ca _pthread_wqthread
20  0x114569c4d start_wqthread
file:///app/tns_modules/nativescript-audio/ios/player.js:159:34: JS ERROR TypeError: null is not an object (evaluating '_this._player.delegate = _this')
```

my project is in Angular 4 using tns 3.3.0

Android and iOS version : 
"tns-android": {
     "version": "3.3.1"
},
"tns-ios": {
    "version": "3.3.0"
}

NPM: 
"nativescript-audio": "^4.3.1",
"angular/animations": "~4.4.1",
"angular/common": "~4.4.1",
"angular/compiler": "~4.4.1",
"angular/core": "~4.4.1",
"angular/forms": "~4.4.1",
"angular/http": "~4.4.1",
"angular/platform-browser": "~4.4.1",
"angular/router": "~4.4.1"

Please help.. thanks 👍

**Comment by bradmartin** [comment]
Can you provide the relevant code to what you have in regard to the TNSPlayer instance? 👍

**Comment by ptdede** [comment]
Yes, please look at my code. 
I load the audio from Url.

`
export class aComponent implements OnInit {

    private _audioPlayer: TNSPlayer

    constructor () {}

    ngOnInit(): void {

        this._audioPlayerConfiguration()
    }

    
    /**
     * Config Audio Player instance
     */
    public currentDuration: string = "00:00 | 00:00"
    public currentDurationValue: number = 0
    public isPlay: boolean = false
    private _totalDuration: number = 0;
    private timerId: any
    private _sliderValueChanged: number
    private _audioPlayerConfiguration(): void {

        this._audioPlayer = new TNSPlayer()

        this._audioPlayer
            .initFromUrl({
                audioFile: "http://www.noiseaddicts.com/samples_1w72b820/4202.mp3",
                loop: false,
                completeCallback: () => {
                    this.isPlay = false
                    this.currentDurationValue = 0
                    this.currentDuration = this._millisToMinutesAndSeconds(this._totalDuration) + " | " + this._millisToMinutesAndSeconds(this._totalDuration)
                },
                errorCallback: () => {
                    this.isPlay = false
                    this.currentDurationValue = 0
                    this.currentDuration = this._millisToMinutesAndSeconds(this._totalDuration) + " | " + this._millisToMinutesAndSeconds(this._totalDuration)
                }
            })
            .then(() => {

                this._audioPlayer.getAudioTrackDuration()
                    .then(duration => {

                        // iOS: duration is in seconds
                        // Android: duration is in milliseconds
                        console.log(`song duration:`, duration);

                        this._totalDuration = parseInt(duration)

                        this.currentDuration = this._millisToMinutesAndSeconds(this._totalDuration) + " | " + this._millisToMinutesAndSeconds(this._totalDuration)

                        this.timerId = setInterval(() => {

                            if (!this._audioPlayer.isAudioPlaying()) {

                                // this.calculateRemainingBufferMedia(parseInt(duration), parseInt(duration), 7)

                                return
                            }

                            let currentRemainingDuration = parseInt(duration) - this._audioPlayer.currentTime

                            if (parseInt(duration) > 0)
                                this.currentDuration = this._millisToMinutesAndSeconds(currentRemainingDuration) + " | " + this._millisToMinutesAndSeconds(parseInt(duration))

                            // this.calculateRemainingBufferMedia(currentRemainingDuration, parseInt(duration), 7)
                            this.calculateRemainingBufferMedia(currentRemainingDuration, parseInt(duration))

                        }, 1000)

                    })

                this.isPlay = true
                this._audioPlayer.play()
            })
    }

}
`

**Comment by NL33** [comment]
Same problem here. Any solutions?

**Comment by markomiljkovic** [comment]
Yes Im getting same Issue on IOS when there is no sound app just crashes...
Anybody got a fix for that????

**Comment by hafizalfaza** [comment]
I ran into the same issue. I hope this issue will be fixed soon before my deadline comes.

**Comment by NL33** [comment]
I have found the error, in my case, happens if:
1) I call the wrong "initFrom..." command. Example, saying "initFromFile" when it should be "initFromURL".
OR:
2) There is a problem with the file itself I am trying to initialize. For example, maybe the file is not properly formatted or maybe I don't have proper permissions to play it. 

In either case, I get the above errors.

There definitely could be other causes of these errors too, but this has been the case for me.
