### ISSUE TITLE
IOS app crash if recieve sms or Usb plugged in

### ISSUE THREAD

**Issue by markomiljkovic** [nstudio/nativescript-audio#96]
Hello guys 
when runing your app and reciving sms while runing code for TNS audio
App crashes and displays error 

"Cannot read propert 'setVolume' of undefined file tns-modules/nativescript-audio/android/player.js line 42 column 37

**Comment by markomiljkovic** [comment]
Anyone ??? Someone ???

**Comment by bradmartin** [comment]
I haven't had any time to look into this myself. Could you share more of your code? You mention iOS in the title but you linked to the `android` player file.

**Comment by markomiljkovic** [comment]
my view
```
const audio = require('nativescript-audio');
const player = new audio.TNSPlayer();

function play(){
 const playerOptions = {
        audioFile: url,  // url is variable where file is located
        loop: false,
        completeCallback() {
             console.log("playback completed");
        },
        errorCallback(errorObject) {
             console.log("Error");
        },
        infoCallback(args) {

        },
    }

    if (player.isAudioPlaying()) {
        player.dispose();
            playIt(playerOptions);
        }
    } else {
        playIt(playerOptions);
    }
}


function playIt(playerOptions){
player.playFromUrl(playerOptions)
        .then((res) => {

    }).catch(() => {

    });
}

```

xml 

`<Button text="play" tap="play"></Button>`

And if I send Sms to myself like this https://ibb.co/dsZLkx
While playing audio or while audio song is loaded app crashes

**Comment by markomiljkovic** [comment]
Here is the screenshot of the error:
https://ibb.co/mUj9TH

**Comment by markomiljkovic** [comment]
I havent tested on IOS because I dont have IOS device, but its happening on Android emulator and also on real device

**Comment by bradmartin** [comment]
this PR might fix your issue https://github.com/nstudio/nativescript-audio/pull/98/files, update has been published to npm

**Comment by markomiljkovic** [comment]
Ok thanx you,
 will test and report if issue still exists

**Comment by markomiljkovic** [comment]
Its working now you can close the task :) 👍
